table tenant_person {
  tenant_id integer [pk, increment]
  full_name varchar(255) [not null]
  date_of_birth date
  phone_number integer
  email integer
  vulnerability_flag boolean [default: false]
}

table tenancy {
  tenancy_id integer [pk, increment]
  tenant_id integer [not null]
  address_id integer [not null]
  start_date date [not null]
  end_date date [not null]
  tenancy_type varchar(100)
  tenancy_status varchar(100)
}

table household_member_person {
  household_member_id integer [pk, increment]
  tenant_id integer [not null]
  tenancy_id integer [not null]
  person_alert_type_id integer
  full_name varchar(255) [not null]
  date_of_birth date
  relationship_to_tenant varchar(100)
  is_contract_holder boolean [default: false]
  vulnerability_details text
  risk_assessment_status varchar(100)
  risk_assessment_date date
}

// Relationships 
Ref: tenancy.tenant_id > tenant_person.tenant_id
Ref: household_member_person.tenancy_id > tenancy.tenancy_id
//Ref: person_alert_type_id > person_alert_type.person_alert_type_id
Ref: household_member_person.tenant_id > tenant_person.tenant_id
//Ref: tenancy.address_id > address.address_id
//Ref: person_alert_type_id > person_alert_type.person_alert_type_id