// DBML script for investigation Module schema
// Author: George Foster (TPXImpact)
// Email: george.foster@tpximpact.com

// Script created for use with dbdiagram.io
// Links to Property, Tenant and Tenancy tables commented out

// search todo for rows needing updates

// Tables

table hazard_type {
  hazard_type_id integer [pk, increment]
  hazard_type nvarchar(100)
  health_risk_rating_id integer
  category nvarchar(500)

  Note: "Stores types of hazards"
  Indexes {
    (health_risk_rating_id)
  }
}


table hazard_report {
  hazard_report_id integer [pk, increment]
  uprn integer
  tenancy_id varchar(50)
  date_reported date
  reported_by nvarchar(100)
  description nvarchar(500)
  photo_evidence nvarchar(500)
  location_details nvarchar(500)
  emergency_action_taken integer [default: 0]
  made_safe_date date
  further_work_required integer [default: 0]
  further_work_due_date date
  report_status_id integer
  investigation_type_id integer

  Note: "Stores hazard reports"
}

table investigation {
  investigation_id integer [pk, increment]
  uprn integer
  tenancy_id varchar(50)
  hazard_report_id integer
  trigger_source_id integer
  investigation_type_id integer
  investigation_scheduled_date date
  investigation_completed_date date
  investigator_id integer
  hazard_confirmed integer [default: 0]
  sla_breach_flag integer [default: 0]
  notification_sent_to_tenant integer [default: 0]
  investigation_notes nvarchar(500)

  Note: "Stores investigation details"
}

table investigation_hazard {
  investigation_hazard_id integer [pk, increment]
  hazard_type_id integer
  investigation_id integer
  hazard_report_id integer
  severity_id integer
  notes nvarchar(500)

  Note: "Maps investigations to hazards"
}

table notification {
  notification_id integer [pk, increment]
  investigation_id integer
  tenancy_id integer
  work_order_id varchar(255)
  notification_type_id integer
  escalation_id integer
  date_sent date
  notification_method_id integer
  content_summary nvarchar(500)

  Note: "Notifications related to investigations"
}

table escalation {
  escalation_id integer [pk, increment]
  investigation_id integer
  escalation_reason nvarchar(100)
  escalation_stage_id integer
  escalation_type_id integer
  escalated_to nvarchar(100)
  escalation_start_date date
  escalation_end_date date
  action_taken nvarchar(500)
  compensation_amount decimal(10,2)
  alternative_accommodation_details nvarchar(500)
  tenant_acceptance integer [default: 0]
  escalation_notes nvarchar(500)

  Note: "Tracks escalation actions"
}

// Code Lists

table health_risk_rating {
  health_risk_rating_id integer [pk, increment]
  health_risk_rating nvarchar(20)
}

table severity {
  severity_id integer [pk, increment]
  severity nvarchar(20)
}

table investigation_type {
  investigation_type_id integer [pk, increment]
  investigation_type nvarchar(20)
}

table report_status {
  report_status_id integer [pk, increment]
  report_status nvarchar(20)
}

table trigger_source {
  trigger_source_id integer [pk, increment]
  trigger_source nvarchar(20)
}

table escalation_status {
  escalation_status_id integer [pk, increment]
  escalation_status nvarchar(20)
}

table notification_type {
  notification_type_id integer [pk, increment]
  notification_type nvarchar(20)
}

table escalation_stage {
  escalation_stage_id integer [pk, increment]
  escalation_stage nvarchar(20)
}

table notification_method {
  notification_method_id integer [pk, increment]
  notification_method nvarchar(20)
}

table escalation_type {
  escalation_type_id integer [pk, increment]
  escalation_type nvarchar(30)
}

table investigator {
  investigator_id integer [pk, increment]
  investigator_name nvarchar(100)
}

// Relationships
ref: hazard_type.health_risk_rating_id > health_risk_rating.health_risk_rating_id
//ref: hazard_report.uprn > address.uprn
//ref: hazard_report.tenancy_id > tenancy.tenancy_id
ref: hazard_report.report_status_id > report_status.report_status_id
ref: hazard_report.investigation_type_id > investigation_type.investigation_type_id
//ref: investigation.uprn > address.uprn
//ref: investigation.tenancy_id > tenancy.tenancy_id
ref: investigation.hazard_report_id > hazard_report.hazard_report_id
ref: investigation.trigger_source_id > trigger_source.trigger_source_id
ref: investigation.investigation_type_id > investigation_type.investigation_type_id
ref: investigation_hazard.hazard_type_id > hazard_type.hazard_type_id
ref: investigation_hazard.investigation_id > investigation.investigation_id
ref: investigation_hazard.hazard_report_id > hazard_report.hazard_report_id
ref: investigation_hazard.severity_id > severity.severity_id
ref: investigation.investigator_id > investigator.investigator_id
ref: notification.investigation_id > investigation.investigation_id
//ref: notification.tenancy_id > tenancy.tenancy_id
//ref: notification.work_order_id > work_order.work_order_id
ref: notification.notification_type_id > notification_type.notification_type_id
ref: notification.notification_method_id > notification_method.notification_method_id
ref: notification.escalation_id > escalation.escalation_id
ref: escalation.investigation_id > investigation.investigation_id
ref: escalation.escalation_stage_id > escalation_stage.escalation_stage_id
ref: escalation.escalation_type_id > escalation_type.escalation_type_id
