Table ContractorOrganisation {
  ContractorOrganisationID varchar PK
  Name varchar
  ContractorPortal varchar
  Subcontractors text
}

Table WorkClass {
  WorkClassID varchar PK
  WorkClassCodeID varchar
  WorkClassCode varchar
  WorkClassDescription text
}

Table WorkPriority {
  WorkPriorityID varchar PK
  WorkPriorityCodeID varchar
  WorkPriorityCode varchar
  WorkPriorityDescription text
  EffectiveDateTime timestamp
  NumberOfDays int
  Comments text
  RequiredStartDate date
  RequiredCompletionDate date
}

Table TradeCode {
  TradeID varchar PK
  TradeCodeID varchar
  TradeCode varchar
  CustomCode varchar
  CustomName varchar
}

Table RateScheduleItem {
  RateScheduleItemID varchar PK
  RateScheduleItemCodeID varchar
  M3NHFSORCode varchar
  Quantity decimal
  CustomCode varchar
  CustomName varchar
}

Table WorkOrder {
  WorkOrderID varchar PK
  WorkElementID varchar
  AddressID varchar
  InspectionID varchar
  EscalationID varchar
  TenancyID varchar
  TenantID varchar
  HazardReportID varchar
  WorkClassID varchar
  LocationAlertID varchar
  PersonAlertID varchar
  WorkPriorityID varchar
  ContractorOrganisationID varchar
  DateRaised date
  DateReported date
  PlannedStartDate date
  PlannedFinishDate date
  ActualStartDateTime timestamp
  ActualCompletionDateTime timestamp
  DescriptionOfWork text
  EstimatedCost decimal
  EstimatedLabourHours decimal
  LocationOfRepair varchar
  JobStatusUpdate varchar
  RepairSLABreachFlag varchar
}

Table WorkElement {
  WorkElementID varchar PK
  WorkOrderID varchar
  RateScheduleItemID varchar
  TradeCode varchar
  ServiceChargeSubject varchar
}

Table WorkElementDependency {
  WorkElementID varchar PK
  DependsOnWorkElementID varchar
  Type varchar
  Timing varchar
  Description text
}

Table WorkOrderStatusHistory {
  WorkOrderStatusHistoryID varchar PK
  WorkOrderID varchar
  StatusCode varchar
  UpdatedBy varchar
  Reason text
  ReasonCode varchar
  CreatedDateTime timestamp
  EnteredDateTime timestamp
  ExistedDateTime timestamp
  Comments text
}

Table WorkOrderComplete {
  WorkOrderCompleteID varchar PK
  WorkOrderID varchar
  BillOfMeterialItem varchar
  CompletedWorkElements text
  OperativesUsed text
  JobStatusUpdate varchar
  FollowOnWork varchar
}

Table WorkOrderAccessInformation {
  WorkOrderAccessInformationID varchar PK
  WorkOrderID varchar
  Description varchar
  KeySafe text
}

Table AlertRegardingLocation {
  LocationAlertID varchar PK
  LocationAlertCodeID varchar
  AlertType varchar
  Attachments text
  Comments text
}

Table AlertRegardingPerson {
  PersonAlertID varchar PK
  PersonalAlertCodeID varchar
  AlertType varchar
  Comments text
}



Ref: WorkOrder.WorkClassID > WorkClass.WorkClassID
Ref: WorkOrder.WorkPriorityID > WorkPriority.WorkPriorityID
Ref: WorkOrder.ContractorOrganisationID > ContractorOrganisation.ContractorOrganisationID
Ref: WorkOrder.LocationAlertID > AlertRegardingLocation.LocationAlertID
Ref: WorkOrder.PersonAlertID > AlertRegardingPerson.PersonAlertID
Ref: WorkElement.WorkOrderID > WorkOrder.WorkOrderID
Ref: WorkElement.RateScheduleItemID > RateScheduleItem.RateScheduleItemID
Ref: WorkElement.TradeCodeID > TradeCode.TradeCodeID
Ref: WorkElementDependency.WorkElementID > WorkElement.WorkElementID
Ref: WorkElementDependency.DependsOnWorkElementID > WorkElement.WorkElementID
Ref: WorkOrderStatusHistory.WorkOrderID > WorkOrder.WorkOrderID
Ref: WorkOrderComplete.WorkOrderID > WorkOrder.WorkOrderID
Ref: WorkOrderAccessInformation.WorkOrderID > WorkOrder.WorkOrderID
Ref: AlertRegardingLocation.LocationAlertCodeID > LocationAlertTypeCode.LocationAlertCodeID
Ref: AlertRegardingPerson.PersonalAlertCodeID > PersonAlertTypeCode.PersonalAlertCodeID
Ref: WorkPriority.WorkPriorityCodeID > WorkPriorityCode.WorkPriorityCodeID
Ref: WorkClass.WorkClassCodeID > WorkClassCode.WorkClassCodeID



